# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Asker.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_AgriculturePredictionModel(object):
    def setupUi(self, AgriculturePredictionModel):
        AgriculturePredictionModel.setObjectName("AgriculturePredictionModel")
        AgriculturePredictionModel.resize(753, 545)
        self.label = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label.setGeometry(QtCore.QRect(10, 10, 191, 21))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_2.setGeometry(QtCore.QRect(20, 50, 111, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_3.setGeometry(QtCore.QRect(20, 80, 111, 20))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_4.setGeometry(QtCore.QRect(20, 110, 161, 20))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_5.setGeometry(QtCore.QRect(20, 140, 161, 20))
        self.label_5.setObjectName("label_5")
        self.pushButton = QtWidgets.QPushButton(AgriculturePredictionModel)
        self.pushButton.setGeometry(QtCore.QRect(630, 480, 94, 36))
        self.pushButton.setObjectName("pushButton")
        self.label_6 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_6.setGeometry(QtCore.QRect(20, 170, 141, 20))
        self.label_6.setObjectName("label_6")
        self.comboBox = QtWidgets.QComboBox(AgriculturePredictionModel)
        self.comboBox.setGeometry(QtCore.QRect(180, 110, 161, 21))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox_2 = QtWidgets.QComboBox(AgriculturePredictionModel)
        self.comboBox_2.setGeometry(QtCore.QRect(180, 140, 161, 21))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_3 = QtWidgets.QComboBox(AgriculturePredictionModel)
        self.comboBox_3.setGeometry(QtCore.QRect(180, 170, 161, 21))
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_4 = QtWidgets.QComboBox(AgriculturePredictionModel)
        self.comboBox_4.setGeometry(QtCore.QRect(180, 200, 161, 21))
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.label_7 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_7.setGeometry(QtCore.QRect(20, 200, 141, 20))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_8.setGeometry(QtCore.QRect(20, 230, 141, 20))
        self.label_8.setObjectName("label_8")
        self.comboBox_5 = QtWidgets.QComboBox(AgriculturePredictionModel)
        self.comboBox_5.setGeometry(QtCore.QRect(180, 230, 161, 21))
        self.comboBox_5.setObjectName("comboBox_5")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.comboBox_5.addItem("")
        self.line = QtWidgets.QFrame(AgriculturePredictionModel)
        self.line.setGeometry(QtCore.QRect(10, 30, 711, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_9 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_9.setGeometry(QtCore.QRect(20, 269, 141, 21))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_10.setGeometry(QtCore.QRect(360, 270, 131, 20))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_11.setGeometry(QtCore.QRect(20, 310, 141, 31))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_12.setGeometry(QtCore.QRect(360, 320, 101, 20))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_13.setGeometry(QtCore.QRect(20, 360, 141, 21))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(AgriculturePredictionModel)
        self.label_14.setGeometry(QtCore.QRect(360, 360, 81, 20))
        self.label_14.setObjectName("label_14")
        self.lineEdit = QtWidgets.QLineEdit(AgriculturePredictionModel)
        self.lineEdit.setGeometry(QtCore.QRect(180, 80, 541, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(AgriculturePredictionModel)
        self.lineEdit_2.setGeometry(QtCore.QRect(180, 50, 541, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(AgriculturePredictionModel)
        self.lineEdit_3.setGeometry(QtCore.QRect(180, 260, 161, 34))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(AgriculturePredictionModel)
        self.lineEdit_4.setGeometry(QtCore.QRect(180, 310, 161, 34))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(AgriculturePredictionModel)
        self.lineEdit_5.setGeometry(QtCore.QRect(180, 360, 161, 34))
        self.lineEdit_5.setObjectName("lineEdit_5")

        self.retranslateUi(AgriculturePredictionModel)
        QtCore.QMetaObject.connectSlotsByName(AgriculturePredictionModel)

    def retranslateUi(self, AgriculturePredictionModel):
        _translate = QtCore.QCoreApplication.translate
        AgriculturePredictionModel.setWindowTitle(_translate("AgriculturePredictionModel", "Agriculture Prediction Model"))
        self.label.setText(_translate("AgriculturePredictionModel", "Input the Values"))
        self.label_2.setText(_translate("AgriculturePredictionModel", "Block Name :"))
        self.label_3.setText(_translate("AgriculturePredictionModel", "Variety Name "))
        self.label_4.setText(_translate("AgriculturePredictionModel", "System Of Cultivation"))
        self.label_5.setText(_translate("AgriculturePredictionModel", "Sources Of Seed "))
        self.pushButton.setText(_translate("AgriculturePredictionModel", "Submit"))
        self.label_6.setText(_translate("AgriculturePredictionModel", "Is Field Irrigated"))
        self.comboBox.setItemText(0, _translate("AgriculturePredictionModel", " Conventional"))
        self.comboBox.setItemText(1, _translate("AgriculturePredictionModel", " SRi"))
        self.comboBox_2.setItemText(0, _translate("AgriculturePredictionModel", " Own Source"))
        self.comboBox_2.setItemText(1, _translate("AgriculturePredictionModel", " Departmental Source"))
        self.comboBox_2.setItemText(2, _translate("AgriculturePredictionModel", " Private Source"))
        self.comboBox_3.setItemText(0, _translate("AgriculturePredictionModel", " Irrigated"))
        self.comboBox_3.setItemText(1, _translate("AgriculturePredictionModel", " Un-irrigated"))
        self.comboBox_3.setItemText(2, _translate("AgriculturePredictionModel", " Rainfed"))
        self.comboBox_3.setItemText(3, _translate("AgriculturePredictionModel", " No"))
        self.comboBox_4.setItemText(0, _translate("AgriculturePredictionModel", " High Yielding Variety"))
        self.comboBox_4.setItemText(1, _translate("AgriculturePredictionModel", " Local"))
        self.comboBox_4.setItemText(2, _translate("AgriculturePredictionModel", " Hybrid"))
        self.label_7.setText(_translate("AgriculturePredictionModel", "Crop Variety Type"))
        self.label_8.setText(_translate("AgriculturePredictionModel", "Water Source"))
        self.comboBox_5.setItemText(0, _translate("AgriculturePredictionModel", " Canal"))
        self.comboBox_5.setItemText(1, _translate("AgriculturePredictionModel", " Submersible Pump"))
        self.comboBox_5.setItemText(2, _translate("AgriculturePredictionModel", " Tank"))
        self.comboBox_5.setItemText(3, _translate("AgriculturePredictionModel", " None"))
        self.comboBox_5.setItemText(4, _translate("AgriculturePredictionModel", " Other"))
        self.label_9.setText(_translate("AgriculturePredictionModel", "Damage by Pests"))
        self.label_10.setText(_translate("AgriculturePredictionModel", "Numeric Value"))
        self.label_11.setText(_translate("AgriculturePredictionModel", "Operational Size holding"))
        self.label_12.setText(_translate("AgriculturePredictionModel", "In hectares"))
        self.label_13.setText(_translate("AgriculturePredictionModel", "Area Under Crop"))
        self.label_14.setText(_translate("AgriculturePredictionModel", "In hectares"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AgriculturePredictionModel = QtWidgets.QDialog()
    ui = Ui_AgriculturePredictionModel()
    ui.setupUi(AgriculturePredictionModel)
    AgriculturePredictionModel.show()
    sys.exit(app.exec_())

